#pragma once 

#define ALEO_ADI __device__ __forceinline__

#if defined(__CUDACC__) // NVCC
   #define ALEO_ALIGN(n) __align__(n)
#elif defined(__GNUC__) // GCC
  #define ALEO_ALIGN(n) __attribute__((aligned(n)))
#elif defined(_MSC_VER) // MSVC
  #define ALEO_ALIGN(n) __declspec(align(n))
#else
  #error "Please provide a definition for ALEO_ALIGN macro for your host compiler!"
#endif

#define MAKE_CODE_CONTEXT_CONCAT(a,b) a##b


#define ALEO_ITER_32_CODE_WITH_2_PARAMS(_CREATE_CODE, p1) \
_CREATE_CODE(p1,0);_CREATE_CODE(p1,1);_CREATE_CODE(p1,2);_CREATE_CODE(p1,3);_CREATE_CODE(p1,4);_CREATE_CODE(p1,5);_CREATE_CODE(p1,6);_CREATE_CODE(p1,7);\
_CREATE_CODE(p1,8);_CREATE_CODE(p1,9);_CREATE_CODE(p1,10);_CREATE_CODE(p1,11);_CREATE_CODE(p1,12);_CREATE_CODE(p1,13);_CREATE_CODE(p1,14);_CREATE_CODE(p1,15);\
_CREATE_CODE(p1,16);_CREATE_CODE(p1,17);_CREATE_CODE(p1,18);_CREATE_CODE(p1,19);_CREATE_CODE(p1,20);_CREATE_CODE(p1,21);_CREATE_CODE(p1,22);_CREATE_CODE(p1,23);\
_CREATE_CODE(p1,24);_CREATE_CODE(p1,25);_CREATE_CODE(p1,26);_CREATE_CODE(p1,27);_CREATE_CODE(p1,28);_CREATE_CODE(p1,29);_CREATE_CODE(p1,30);_CREATE_CODE(p1,31);

#define ALEO_ITER_8_CODE_WITH_2_PARAMS(_CREATE_CODE, p1) \
_CREATE_CODE(p1,0);_CREATE_CODE(p1,1);_CREATE_CODE(p1,2);_CREATE_CODE(p1,3);_CREATE_CODE(p1,4);_CREATE_CODE(p1,5);_CREATE_CODE(p1,6);_CREATE_CODE(p1,7);


#define ALEO_ITER_8_CODE(_CREATE_CODE) \
_CREATE_CODE(0);_CREATE_CODE(1);_CREATE_CODE(2);_CREATE_CODE(3);_CREATE_CODE(4);_CREATE_CODE(5);_CREATE_CODE(6);_CREATE_CODE(7);

#define ALEO_ITER_32_CODE(_CREATE_CODE) \
_CREATE_CODE(0);_CREATE_CODE(1);_CREATE_CODE(2);_CREATE_CODE(3);_CREATE_CODE(4);_CREATE_CODE(5);_CREATE_CODE(6);_CREATE_CODE(7);\
_CREATE_CODE(8);_CREATE_CODE(9);_CREATE_CODE(10);_CREATE_CODE(11);_CREATE_CODE(12);_CREATE_CODE(13);_CREATE_CODE(14);_CREATE_CODE(15);\
_CREATE_CODE(16);_CREATE_CODE(17);_CREATE_CODE(18);_CREATE_CODE(19);_CREATE_CODE(20);_CREATE_CODE(21);_CREATE_CODE(22);_CREATE_CODE(23);\
_CREATE_CODE(24);_CREATE_CODE(25);_CREATE_CODE(26);_CREATE_CODE(27);_CREATE_CODE(28);_CREATE_CODE(29);_CREATE_CODE(30);_CREATE_CODE(31);

